### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by nkdweb** [nigharsh/flipkart-affiliate-client#3]
When i try to implement, i got 401 Unauthorized.

As i see

Access-Control-Request-Headers | access-control-allow-origin,fk-affiliate-Id,fk-affiliate-token are inserted in Access-Control-Request-Headers.

I'm using angular version 5, please guide me how to authenticate flipkart affiliate API.

**Comment by nigharsh** [comment]
This project is no longer being maintained. Feel free to create a pull request.

**Comment by amannguptaggg** [comment]
how i can use flipkart affiliate api in angular 8 cli please help
